# Generated by Django 5.2.4 on 2025-07-30 14:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("FAILED_LOGIN", "Failed Login"),
                            ("LOGOUT", "User Logout"),
                            ("CREATE", "Record Created"),
                            ("UPDATE", "Record Updated"),
                            ("DELETE", "Record Deleted"),
                            ("VIEW", "Record Viewed"),
                            ("EXPORT", "Data Exported"),
                        ],
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        help_text="Resource affected (e.g., User, Product, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the affected resource",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="IP address of the user"),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string", null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the action occurred",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        help_text="Severity level of the action",
                        max_length=10,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional details about the action",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Session ID when action occurred",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_logs_user_id_e11c73_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="audit_logs_action_f48619_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="audit_logs_ip_addr_345630_idx",
                    ),
                    models.Index(
                        fields=["severity", "-timestamp"],
                        name="audit_logs_severit_83c56b_idx",
                    ),
                ],
            },
        ),
    ]
